# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20170117_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/subjects'),
        ),
    ]
